<a href="https://colab.research.google.com/github/angelgomes06-ops/Case_Aula_29_Julho/blob/main/exemplos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd

# quando tinhamos arquivos csv
# pd. read_csv ('nome do arquivo')

dados_musica = '/playlist_hits (1).json'


#df quer dizer data frame - pedaço/parte do dado

df_dados_musica = pd.read_json(dados_musica)

#ver a informação - display(df.head(numero))
display(df_dados_musica.head())

#quero construir uma nova coluna na base de dados
# essa coluna vai se chamar "categoria_tamanho"
# sempre que a musica for maior que 300s é grande se não é pequeno

#1° vamos colocar todos os valores da coluna "duracao_seg" dentro de uma lista
list_tamanho_musica = []

#2° transformar uma coluna em lista
list_duracoes =df_dados_musica ['duracao_seg'].tolist()
#o comando .tolist() faz a coluna virar uma lista python
# quero que sempre que a duração for mauor ou igual a 300, salvar na
# list_tamanho_musica o valor 'musica grande' e quando for menor que 300 salvar
# salvar 'musica curta'

for i in list_duracoes:
  if i >= 300:
    list_tamanho_musica.append('musica grande')
  else:
    list_tamanho_musica.append('musica curta')

    # criar uma nova coluna
df_dados_musica ['categoria_tamanho'] = list_tamanho_musica

display (df_dados_musica.head())

,id,titulo,artista,genero,streams_milhoes,duracao_seg
0,1,Master of Puppets,Metallica,Rock,520,515
1,2,Blinding Lights,The Weeknd,Pop,3400,200
2,3,Star Wars Main Theme,John Williams,Trilha Sonora,150,320
3,4,Bohemian Rhapsody,Queen,Rock,2100,354
4,5,Levitating,Dua Lipa,Pop,1800,203

,id,titulo,artista,genero,streams_milhoes,duracao_seg,categoria_tamanho
0,1,Master of Puppets,Metallica,Rock,520,515,musica grande
1,2,Blinding Lights,The Weeknd,Pop,3400,200,musica curta
2,3,Star Wars Main Theme,John Williams,Trilha Sonora,150,320,musica grande
3,4,Bohemian Rhapsody,Queen,Rock,2100,354,musica grande
4,5,Levitating,Dua Lipa,Pop,1800,203,musica curta

In [ ]:
# de uma data frame eu consigo tirar métricas
#.metrica()

# valor médio de todos os streams
media_stream = df_dados_musica['streams_milhoes'].mean()
print (media_stream)

In [21]:
# métricas estatistica básicas nativas do python
# somar todo um conjunto de dados .sum()
# encontrar a média de um conjunto de dados .mean()
# maior valor de um conjunto de dados .max()
# menor valor de um conjunto de dados .min
# contar valores de um conjunto de dados .value_counts()
# descrever o conjunto de dados .describe
# informações relevantes do conjunto de dados .info()
# valor que aparece com maior frequencia .idmax()
# moda .mode()
# mediana .median()

# posso criar um filtro, por exemplo, mostrar apenas as musicas do genero Pop

# um filtro simples sempre é:
df_dados_musica_pop = df_dados_musica[df_dados_musica ['genero'] == 'Pop']
# criar um novo df que vai receber a base original.
# so que a base original deve ter seu campo indexado com ela mesmo + filtro
# exemplo df_original[df_original['FILTRO']] == VALOR_FILTRO']
display (df_dados_musica_pop)

# agora queremos saber o total das streams
print (f'o total de streams é de {df_dados_musica ['streams_milhoes'].sum()}')
print('\n\n')
# agora queremos saber o total de streams do genero rock
# 1° criar um filtro para a metrica
df_dados_musica_rock = df_dados_musica[df_dados_musica['genero'] == 'Rock']
print(f'a media de streams de rock é {df_dados_musica_rock['streams_milhoes'].mean()}')

,id,titulo,artista,genero,streams_milhoes,duracao_seg,categoria_tamanho
1,2,Blinding Lights,The Weeknd,Pop,3400,200,musica curta
4,5,Levitating,Dua Lipa,Pop,1800,203,musica curta

o total de streams é de 9570



a media de streams de rock é 1406.6666666666667

In [23]:
# filtro simples, mas com dois criterios

#metodo do .isin()
filtro_trilha_pop = ['Pop', 'Trilha Sonora']

df_dados_musica_pop_trilha = df_dados_musica[df_dados_musica['genero'].isin(filtro_trilha_pop)]

display(df_dados_musica_pop_trilha)

,id,titulo,artista,genero,streams_milhoes,duracao_seg,categoria_tamanho
1,2,Blinding Lights,The Weeknd,Pop,3400,200,musica curta
2,3,Star Wars Main Theme,John Williams,Trilha Sonora,150,320,musica grande
4,5,Levitating,Dua Lipa,Pop,1800,203,musica curta

In [38]:
import pandas as pd

df_entregas = pd.read_csv('/content/entregas_orquideas.csv')
df_qualidade = pd.read_csv('/content/estufas_qualidade.csv')
df_telemetria = pd.read_csv('/content/telemetria_iot.csv')

# Renomear a sexta coluna (índice 5) de df_entregas para 'Status'
current_columns_entregas = df_entregas.columns.tolist()
# A sexta coluna é o índice 5 (começando do zero)
current_columns_entregas[5] = 'Status'
df_entregas.columns = current_columns_entregas

df_entregas.head()
df_qualidade.head()
df_telemetria.head()


# criar lista vazia
status_temperatura = []

#Laço de repetição para percorrer a coluna de temperaturas
for temperatura in df_telemetria['Temperatura_C']:
  if temperatura >= 28:
    status_temperatura.append("ALERTA")
  else:
    status_temperatura.append('OK')

# add lista como nova coluna
df_telemetria['status_temperatura'] = status_temperatura

# exibir linhas
df_telemetria.head()

# Quant. transportadas de orquídeas
total_orquideas = df_entregas["Qtd_Orquideas"].sum()
print(f'Quantidade total de orquídeas transportadas: {total_orquideas}')

# Prejuízo final
total_perdidas = df_entregas[df_entregas['Status'] == 'Cancelado']['Qtd_Orquideas'].sum()
print(f'Quantidade total de orquídeas canceladas: {total_perdidas}')

# Impacto Regional
estado_mais_afetado = (
    df_entregas[df_entregas["Status"] == "Cancelado"]["UF_Destino"]
    .value_counts()
    .idxmax()
)

print("Estado com mais entregas canceladas:", estado_mais_afetado)

# Análise de temperatura
temperatura_max = df_telemetria["Temperatura_C"].max()
temperatura_media = df_telemetria["Temperatura_C"].mean()

print("Temperatura máxima:", temperatura_max)
print("Temperatura média:", temperatura_media)

Quantidade total de orquídeas transportadas: 55425
Quantidade total de orquídeas canceladas: 6349
Estado com mais entregas canceladas: SP
Temperatura máxima: 34
Temperatura média: 27.0